### ISSUE TITLE
Laden von Paket caption

### ISSUE THREAD

**Issue by hvoss49** [rolfn/xltabular#1]
Das hat mich Grübeln gekostet, um herauszufinden, welches Paket querschießt ...

```
\documentclass[openany]{book}
\usepackage{caption}%% führt dazu, dass im 1. Kapitel nicht gezählt wird
\usepackage{xltabular}
\begin{document}
\chapter{foo}

\begin{xltabular}{\linewidth}{X}
bar
\end{xltabular}

\begin{xltabular}{\linewidth}{X}
\caption{xltabular\label{tab:xl}}\\
bar
\end{xltabular}

\section{Zwei}

\begin{xltabular}{\linewidth}{X}
\caption{xltabular\label{tab:xl2}}\\
bar
\end{xltabular}

\chapter{barbaz}

\begin{table}[!h]
\caption{baz}\label{tab:baz}
\end{table}

Wie~\ref{tab:baz} und ~\ref{tab:xl} zeigt ...
Und auch \ref{tab:xl2}
\end{document}
```

TL 2017 und letzte xltabular

![bildschirmfoto vom 2017-10-23 13-17-58](https://user-images.githubusercontent.com/12891199/31886484-b6dd338e-b7f4-11e7-812a-cf8767d0baa0.png)

**Comment by rolfn** [comment]
"caption" macht die Sache noch etwas komplizierter, aber auch universeller. Es funktioniert jetzt hoffentlich mit und ohne "caption". Es lässt sich auch das Makro \LTcaptype (ggf. zu "figure" umdefinierbar) verwenden wie in der Beschreibung zu "ltcaption" zu sehen.
