### ISSUE TITLE
\endlastfoot has no effect inside mdframed environment

### ISSUE THREAD

**Issue by AdrianVollmer** [rolfn/xltabular#11]
Consider this MWE:

```
\documentclass{article}

\usepackage{xltabular}
\usepackage{mdframed}

\begin{document}

\begin{mdframed}
\begin{xltabular}{\linewidth}{ll}
    foot
\endlastfoot
    one & two \\
\end{xltabular}
\end{mdframed}

\begin{xltabular}{\linewidth}{ll}
    foot
\endlastfoot
    one & two \\
\end{xltabular}
\end{document}
```
This produces two tables. `foot` only appears in the second table. I'd expect it in the first table as well.

Note: This also happens with the `tabularx` environment of the package `ltablex`, but I could not find its issue tracker ...

**Comment by hvoss49** [comment]
It has nothing to do with `xltabular`. It also happens with `longtable`:
```
\documentclass{article}
\usepackage{mdframed}
\usepackage{longtable}
\begin{document}
\begin{mdframed}
\begin{longtable}{ll}%
foot
\endlastfoot
    one & two \\
\end{longtable}
\end{mdframed}
\end{document}
```

Report it to texhax@tug.org

**Comment by AdrianVollmer** [comment]
Done: https://tug.org/pipermail/texhax/2020-June/024430.html

Thank you for the hint
