### ISSUE TITLE
Table counter is increased when not using a caption

### ISSUE THREAD

**Issue by SeeDoubleYou** [rolfn/xltabular#12]
I have a document with multiple xltabulars (17 to be exact) before the first one with a caption. The table counter is 18 at that point whereas, according to the manual of xltabular, it should still be one. I think this error can actually also be seen in the manual itself where an example is given. There the counter goes from 3 to 5 with two captionless tables in between.

**Comment by SeeDoubleYou** [comment]
I now see that there's a difference between the manual I read (this one: http://ftp.snt.utwente.nl/pub/software/tex/macros/latex/contrib/xltabular/xltabular-doc.pdf) and the one in the repo (where it does work correctly). Seems that the package on ctan may be outdated?

**Comment by SeeDoubleYou** [comment]
As an example:
```
\documentclass[10pt, a4paper]{article}

\usepackage{xltabular}

\begin{document}

\begin{xltabular}{\textwidth}{X|X}
Some & Text \\\hline
No & Caption
\end{xltabular}

\begin{xltabular}{\textwidth}{X|X}
  Other & Text \\\hline
  With & Caption \\
  \caption{Table with caption}
\end{xltabular}

\end{document}
```

Renders to
```
Some            | Text
--------------------------
No              | Caption


Other           | Text
--------------------------
With            | Caption

Table 2: Table with caption
```

The second table should be numbered 1, since the first one does not contain a caption.

**Comment by hvoss49** [comment]
you are right. 
Rolf, in the version from TL2019 0.2b it is ok!

**Comment by rolfn** [comment]
The new version fixes the bug. It's  on the way to CTAN.

**Comment by SeeDoubleYou** [comment]
Great thanks. Once it is available on CTAN I'll give it another go.
