### ISSUE TITLE
 ignoring duplicate destination with the name 'table.2.0'

### ISSUE THREAD

**Issue by krumeich** [rolfn/xltabular#2]
Thank you so much for providing a package to remedy the longtable/tabularx problem. Really appreciate it.

There is a small issue, however: In our use case, we have a script that generates many tables. These tables do not need a caption. From what I understood of `xltabular.sty` a  captionless table doesn't increase the counter, which -- when using hyperref with LuaLaTeX -- leads to the following warning: 

`(pdf backend): ignoring duplicate destination with the name 'table.2.0'`

I don't know who or what adds `table.2.0`, but it's a bit annoying. This doesn't happen when we use plain longtable environments. Do you have an idea what causes this and how to fix it? Thanks!

**Comment by hvoss49** [comment]
try to load hyperref with

     \usepackage[plainpages,...]{hyperref}

**Comment by krumeich** [comment]
Thanks for the quick reply. Unfortunately, loading hyperref with

`\usepackage[plainpages,unicode]{hyperref}`

didn't change the warning.

**Comment by hvoss49** [comment]
In my example it worked. Please provide a short and complete example which shows the behaviour

**Comment by krumeich** [comment]
Here's a mwe that reproduces the problem, albeit the warning is "table.0.0" instead of the text in the original post.

[mwe.zip](https://github.com/rolfn/xltabular/files/2667197/mwe.zip)

Just found out that running the example with `pdflatex` does not produce the warning. `lualatex`, on the other hand, prints the warning. I'm using a recently updated TeXLive 2018 for this, btw.

**Comment by hvoss49** [comment]
next try: Write before the first `xltabular` which has no caption:
```
\makeatletter
\let\longtable\ORIG@longtable
\makeatother
```

**Comment by krumeich** [comment]
That did it! I'll apply this patch to the original document and see if it works in the larger context. For now, we can close the issue. Thanks a lot for the quick help!

**Comment by hvoss49** [comment]
It is only a workaround and works only if there are no more tabulars with a caption after that definition.

**Comment by rolfn** [comment]
We have rewritten the parts for supporting hyperref (version 0.2.a). Hopefully the interaction is now more robust. Please try it. Thank you for the bug report.

**Comment by krumeich** [comment]
Works well! Thank you!
