### ISSUE TITLE
Regression on warnings

### ISSUE THREAD

**Issue by krumeich** [rolfn/xltabular#4]
Today I noticed that the warnings mentioned in #2 have reappeared. It seems that 414f8a75 has introduced a regression. When I check out the previous commit (002f16bb) everything works as expected. Could you kindly take a moment to look into this? Thank you!

**Comment by rolfn** [comment]
I will try to resolve the new/old problem in some days. It's not easy...

**Comment by rolfn** [comment]
Hello Alexander,
I tried to resolve your Problem but I can't reproduce it. I call
```
lualatex mwe.tex
```
with the newest version of »xltabular« (`2019/01/30 v0.2b`) and I get no warnings. Please give me more hints. Add `\listfiles` before `\begin{document}` and show me the list of packages at the end of the `.log` file. 

Rolf

**Comment by krumeich** [comment]
Sorry for keeping this open for so long. I've just installed TeXLive 2019. 

The example below (sorry for renaming the file) shows the warning

> warning  (pdf backend): ignoring duplicate destination with the name 'table.1'

As requested, I've added \listfiles so you can see what files are loaded in the logfile.

Thanks for looking into this!

Alexander



[test.tex.txt](https://github.com/rolfn/xltabular/files/3237022/test.tex.txt)
[test.log](https://github.com/rolfn/xltabular/files/3237018/test.log)

**Comment by rolfn** [comment]
I can confirm this issue. I will try to find out what happens.

**Comment by krumeich** [comment]
Any progress on this issue? Anything I can try to help?

**Comment by rolfn** [comment]
I think it's a matter of the order. The package `xltabular` should be loaded **after** `hyperref` in this case:
```latex
\listfiles
\documentclass[a4paper]{article}
\usepackage{hyperref}
\usepackage{xltabular}

\begin{document}

\begin{xltabular}[c]{\linewidth}{XXXX}
  Column 1 & Column 2 & Column 3 & Column 4 \\
  Column 1 & Column 2 & Column 3 & Column 4 \\
  \caption{4 beautiful columns}
\end{xltabular}

\end{document}
```

**Comment by krumeich** [comment]
Thank you! I can confirm that package order is the culprit here -- at least for the MWE. With my production code I still see loads of warnings. However there are many more packages involved, so I guess I need to analyze this a bit further with respect to implicit package loading. Thanks so far! Let's close this issue for now.
