### ISSUE TITLE
[feature proposal] rowfont command

### ISSUE THREAD

**Issue by c-alpha** [rolfn/xltabular#5]
I am hitting a couple of bugs in `tabu` with my document class. Hence I am looking for a replacement, and am currently investigating `xltabular`. So far things look quite promising, and it seems I should be able to replace `tabu` with `xltabular`. Very nice work guys!

The only thing I haven't been able to find an alternate solution for seems to be the `\rowfont` command (and which I am using apparently). Looking at how it is implemented in `tabu` (without understanding too much of it though), and some small experiments, it seems that in order to change the font of all cells in a row, one has to repeat the font setting at the beginning of each cell's content. If this were the case, it would mean that `\rowfont` would need to be implemented as part of `xltabular`, or I'm out of luck.

Hence two questions:

1. Is my guesswork about how changing the font of a table row would need to be done going in the right direction?

1. If yes, would you feel inclined to consider implementing a `\rowfont` command in `xltabular`?

As I'm using the command to give the header row a different look, having the option to also override the horizontal alignment for the row in question:

> `\rowfont [align]{font spec}` Modify the font and optionally the alignment of each cell in one row.

**Comment by rolfn** [comment]
Hello Alexander,
our package is only a wrapper package for `longtable` and `tabularx`. Features like `\rowfont` should be implemented in these packages. 

...Rolf

**Comment by c-alpha** [comment]
Hello Rolf, many thanks for your swift response, and helpful recommendation. Will do.

**Comment by c-alpha** [comment]
p.s.: I'm not the first... https://github.com/latex3/latex2e/issues/176
