### ISSUE TITLE
Page overflow with two tables and float

### ISSUE THREAD

**Issue by brio1009** [rolfn/xltabular#6]
I'm experiencing a page overflow if a float figure and two xltabular tables are on the same page.

![image](https://user-images.githubusercontent.com/3618176/69418833-b62e7f00-0d1b-11ea-9ec4-afbf826dac65.png)

The following files can be used to reproduce the problem:
[demo.zip](https://github.com/rolfn/xltabular/files/3879150/demo.zip)

Any idea how this can be fixed?

**Comment by hvoss49** [comment]
It is a problem with `longtable` and not `xltabular`. Use an individual `\pagebreak` inside the tabular or a `\clearpage` _before_ the `xltabular`.

**Comment by brio1009** [comment]
Thanks, you are right! `xltabular` uses `ltablex` which in turn uses `longtable`.

I was able to fix the problem by patching my local `longtable.sty` as described here: https://www.latex-project.org/cgi-bin/ltxbugs2html?pr=tools/3512
