### ISSUE TITLE
\caption[]{...} not working as expected

### ISSUE THREAD

**Issue by Ri-Ga** [rolfn/xltabular#9]
According to the longtable documentation, "\caption[]{<caption>}" produces a caption with text "Table ?: <caption>" but no entry in the list of tables.

When xltabular is not loaded, the above form of \caption does not increment the counter value when used inside a longtable environment.
When xltabular is loaded, the counter value is incremented in both longtable and xltabular environments. I think, this is a bug and I would prefer the original longtable behavior.

MWE:
```
\documentclass{article}
\usepackage{longtable}
\usepackage{xltabular}% comment this line out to see the difference on page 2

\begin{document}
\listoftables
\section{The Table(s)}

\begin{longtable}{ll}
	\caption[LoT]{Caption}
	\endfirsthead
	\caption[]{(continued)}
	\endhead
	x & y \\
	a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ 
	a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ 
	a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ 
	a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ a\\ 
\end{longtable}
\end{document}
```
This applies to xltabular 2019/01/30 v0.2b and longtable 2020/01/07 v4.13.

**Comment by rolfn** [comment]
Hello,
thank you for reporting this error. I added a new version of `xltabular.sty` (0.2c) which hopefully resolve this issue. Please have a look.

**Comment by Ri-Ga** [comment]
Thanks for the fix. I can confirm that it resolves the issue. Thanks a lot!
